### ISSUE TITLE
A small problem with the calculation of beampattern

### ISSUE THREAD

**Issue by ISmallFish** [PhanLeSon03/SparseArray#1]
> in 'SparseArray_Broadside.m', line 221.  
>> May the 'DP(:,iF)=D*(h);' should be changed to 'DP(:,iF)    = h'*D.';'. 

>> When the look direction 'theta' is not 0°，the peak of beam pattern will be directed to '-theta'. 
> p.s. There is no problem with calculating 'h'.

**Comment by PhanLeSon03** [comment]
yes, there are some ambiguous directions in my code which lead to the direction being inverted. I will correct them in the next version.
Meanwhile, you can correct them by yourself.

**Comment by ISmallFish** [comment]
Thank you~
